# Generated by Django 2.2.1 on 2019-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ticket_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
